DROP TABLE users_pictures;
DROP TABLE sms_messages;
DROP TABLE users;
DROP TABLE operators;
DROP TABLE pictures;
DROP TABLE configuration;
DROP TABLE nicks;
DROP TABLE operator_roles;
DROP TABLE service_provider;